language: java
addons:
  hosts:
    - javasdk
  hostname: javasdk
# The cross product of the jdk and env settings form the matrix of builds Travis will run.
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
env:
  - MODULES_TO_SKIP=\!aws-java-sdk-osgi MAVEN_OPTS=-XX:MaxPermSize=256m
  - MODULES_TO_SKIP=\!aws-java-sdk-osgi,\!aws-java-sdk-code-generator,\!aws-java-sdk-codegen-maven-plugin,\!aws-java-sdk-opensdk MAVEN_OPTS=-XX:MaxPermSize=256m
# Exclude certain items in the matrix as some modules only build with Java8
matrix:
  exclude:
    - jdk: openjdk7
      env: MODULES_TO_SKIP=\!aws-java-sdk-osgi MAVEN_OPTS=-XX:MaxPermSize=256m
    - jdk: oraclejdk7
      env: MODULES_TO_SKIP=\!aws-java-sdk-osgi MAVEN_OPTS=-XX:MaxPermSize=256m
    - jdk: oraclejdk8
      env: MODULES_TO_SKIP=\!aws-java-sdk-osgi,\!aws-java-sdk-code-generator,\!aws-java-sdk-codegen-maven-plugin,\!aws-java-sdk-opensdk MAVEN_OPTS=-XX:MaxPermSize=256m

notifications:
  email:
    - github-awsforjava@amazon.com
install: /bin/true
sudo: required
dist: precise
script: mvn install -Dhttps.protocols=TLSv1.2 -pl ${MODULES_TO_SKIP}
