language: java
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
  - oraclejdk8
env:
  - MODULES_TO_SKIP=\!aws-java-sdk-osgi
  - MODULES_TO_SKIP=\!aws-java-sdk-osgi,\!aws-java-sdk-code-generator,\!aws-java-sdk-codegen-maven-plugin
matrix:
  exclude:
    - jdk: openjdk6
      env: MODULES_TO_SKIP=\!aws-java-sdk-osgi
    - jdk: openjdk7
      env: MODULES_TO_SKIP=\!aws-java-sdk-osgi,\!aws-java-sdk-code-generator,\!aws-java-sdk-codegen-maven-plugin
    - jdk: oraclejdk7
      env: MODULES_TO_SKIP=\!aws-java-sdk-osgi,\!aws-java-sdk-code-generator,\!aws-java-sdk-codegen-maven-plugin
    - jdk: oraclejdk8
      env: MODULES_TO_SKIP=\!aws-java-sdk-osgi,\!aws-java-sdk-code-generator,\!aws-java-sdk-codegen-maven-plugin

install: /bin/true
sudo: required
dist: precise
script: mvn install -pl ${MODULES_TO_SKIP}
